### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by chasingmaxwell** [flatsiedatsie/webthings-network-presence-detection#27] opened 2020-05-23 15:03 UTC
When this add-on is enabled, a python3 process very quickly jumps up to 100% CPU on my raspberry pi 4. I'm listening for the presence of just one device on my network. When I disable this add-on, the process disappears. Seems like an awful lot of load on my processor to occasionally poll for the presence of a single device on my network. What information can I provide to help track down the issue?

**Comment by flatsiedatsie** [comment] 2020-05-24 10:45
Is this continuous?

The latest version of the add-on had a lot of work done to reduce processor usage. It will do a full network scan at boot and about once an hour (trying every IP address), which will be intense. But between those moments processor usage should be light.

**Comment by chasingmaxwell** [comment] 2020-05-24 13:44
I believe it is consistent, I discovered the issue because my processor was consistently hotter than I expected. When I checked the processes that were running, there was a python3 process and node process both at 100%. I restarted the gateway and the node process went away, but the python3 process jumped right back up. Then it went away when I disabled the add-on, and jumped right back up when I enabled it. From what you're saying though, it seems like that initial high usage is expected. I'll try enabling it and see if it drops back down to reasonable amount after a bit.

**Comment by chasingmaxwell** [comment] 2020-05-24 13:58
Before enabling:

![Selection_093](https://user-images.githubusercontent.com/3128659/82755936-ea572b00-9da4-11ea-9b82-3216e431ef1f.jpg)

Directly after enabling

![Selection_094](https://user-images.githubusercontent.com/3128659/82755945-f3e09300-9da4-11ea-8fe1-213960cb1762.jpg)

5 minutes after enabling:

![Selection_095](https://user-images.githubusercontent.com/3128659/82755954-0064eb80-9da5-11ea-922c-12551f2c6261.jpg)

10 minutes after enabling:

![Selection_096](https://user-images.githubusercontent.com/3128659/82755958-0eb30780-9da5-11ea-81f5-16fb62c8e317.jpg)

After disabling:

![Selection_097](https://user-images.githubusercontent.com/3128659/82755962-1672ac00-9da5-11ea-8a8f-e2961fb4201d.jpg)

**Comment by flatsiedatsie** [comment] 2020-05-26 18:14
The full scan should definitely not take more than 3 minutes.

Could you tell me more about your system? Is if on the normal WebThings image? Any special hardware, other software installed, etc. Any errors in internal logs if you enable debug in the add-settings? A full network? Any custom settings for the add-on?

**Comment by flatsiedatsie** [comment] 2020-06-01 22:25
A new version of the add-on has been released. It doesn't address your problem specifically, but you never know, perhaps its fixed?

**Comment by chasingmaxwell** [comment] 2020-06-02 01:15
I updated and it _is_ fixed! Thanks! :smile:

**Comment by flatsiedatsie** [comment] 2020-06-02 12:07
Hey, that's great to hear.

**Comment by chasingmaxwell** [comment] 2020-06-02 16:01
Oh no, looks like I spoke too soon. I had removed the add-on and when I added it back there wasn't an issue so I assumed it was fixed. After running for a day the python3 process was right back up to 100% CPU usage. So it looks like it's some kind of leak that builds up after a while. Previously I hadn't removed the extension I was just disable/enabling it and it would jump right back up to 100 immediately. For now I've disabled the add-on and the python3 process went away just as before.

**Comment by chas-iot** [comment] 2020-06-03 09:45
I installed the new version of the add-on and one CPU jumped to 100% utilisation by a python3 process for several hours.
I rebooted my Raspberry Pi and in the past 18 hours, it seems to be OK.

**Comment by chas-iot** [comment] 2020-06-04 07:38
sadly, the high CPU came back 
![image](https://user-images.githubusercontent.com/65324897/83728853-655bf380-a679-11ea-9a15-8c2d5a3c67eb.png)

**Comment by chasingmaxwell** [comment] 2020-06-04 13:35
I wonder if the hardware is significant. I'm on a raspberry pi 4. Is that what you're on @chas-iot?

**Comment by chas-iot** [comment] 2020-06-04 14:02
> I'm on a raspberry pi 4. Is that what you're on @chas-iot?

yes

**Comment by da-wolff** [comment] 2020-07-30 03:46
I have the same problem, and I am running my WebThings Gateway in a Docker container.

**Comment by flatsiedatsie** [comment] 2020-08-03 07:53
I've created a new version if the addon that I hope will address this issue. Please let me know if this improves the situation.

A few things are changed:
- More over-the-top checking if a scan isn't already running.
- Instead of 5 threads it now only uses 2 threads for scanning. The brute force scan takes a but longer now, but that shouldn't be an issue.
- It turned out the period between brute force scans was too small - I had accidentally letf in a development number. So instead of scanning every 30 minutes, it did so every 5 minutes.

In my own testing I don't see a spike in CPU usage anymore. An easy way to check this yourself if the install the `systeminfo` addon and log the CPU usage. I recommend logging it for 6 hours or so, since it generates a lot of data.

**Comment by chas-iot** [comment] 2020-08-03 10:08
After several hours, I notice that the new version keeps a lot closer track of my iPhone. Here's an annotated graph (the last 12 hours, using Grafana) of before and after
![image](https://user-images.githubusercontent.com/65324897/89171205-6777fb00-d5b3-11ea-9767-5d408bdf7a4b.png)
Note that immediately after upgrade, it did not find my iPhone, so I stopped the python process then disabled and enabled the addon, when it started to see the iPhone.

Just like last time, the python process is using 100% of one core, the RPI has 4 cores.
![image](https://user-images.githubusercontent.com/65324897/89171498-da817180-d5b3-11ea-975d-364c915ab1cd.png)

I appreciate the work you are doing on this. Let me know if I can help by installing an instrumented version ?

**Comment by chas-iot** [comment] 2020-08-03 10:11
Note that the 100% CPU issue was not present immediately after the update. I noticed it several hours later

**Comment by da-wolff** [comment] 2020-08-03 11:48
I noticed the same behaviour. Initially it was going well and then it jumped back to using very high CPU. It could be roughly 30mins after starting I guess.

**Comment by joshkrz** [comment] 2020-08-04 18:29
I'm experiencing the same problem. I'm using the official Docker container on Unraid and I have two processes using 100% of an Intel i3 CPU. I have two devices setup for detection. 

I had the Time Window set to 1 minute, changing this to 5 has seemed to calm the processes down.
 
![Screenshot 2020-08-04 at 19 22 55](https://user-images.githubusercontent.com/6578760/89330469-2f8eb780-d688-11ea-8ef5-d9f732a42b94.png)

EDIT: Unfortunatly im back at 100% CPU again after checking a couple of hours later.

**Comment by chas-iot** [comment] 2020-08-05 03:09
version 1.0.2 made a substantial difference, both good and not so good. I do appreciate the work you are putting in.

The good: the high CPU utilisation seems to have gone.

The not so good: the presence detection does not keep such a close track of my iPhone. Here's a graph of the past 12 hours, where my phone was present all the time and charging from 1am onwards.
![image](https://user-images.githubusercontent.com/65324897/89366952-77eeb980-d70a-11ea-8f99-4507f560fb32.png)
The issue is that the minutes since last seen exceeded 10 minutes around 10 times in less than 12 hours. 10 minutes is my target for rules regarding presence of my phone. The vertical red line roughly indicates the time that I installed the update. The horizontal blue line is at 10 minutes. The y-axis is on a log2 scale, as I am more interested in the details of the small values than the large.

**Comment by flatsiedatsie** [comment] 2020-08-05 10:53
@joshkrz are you sure you're on the latest version? I found a bug that I think was causing the high CPU usage (a while loop around the brute force scan function).

I also increased the time between normal "is the device still there" scans from 5 seconds to 60, to further give the CPU some breathing room. That increase migh be causing of the issue @chas-iot is having.

@da-wolff how is the CPU usage for you now?

Thank you all for your help in improving things.

**Comment by da-wolff** [comment] 2020-08-05 12:06
@flatsiedatsie V1.0.2 is working great for me now !  I have had this running for most of the day today and it seems to be using minimal CPU time now while maintaining the status of two nodes in my network (1 online, 1 mostly offline).  I have not yet witnessed my log of time since last seen go above 1 minute until I dropped my wifi out to test.  My online device is an IOT mains powered wifi node on my network.

@chas-iot I would wonder/suspect that your iPhone may be a little aggressive in putting itself to low power/sleep and failing to respond to pings?  Do you have a mains powered device you can test this with to rule out the battery powered device conserving power rather than the add-on not performing its function.  I can also try the alternative and see how it goes on my end with an Android phone.

**Comment by chas-iot** [comment] 2020-08-05 12:36
@da-wolff iPhones are known to aggressively manage power and that is a good thing :) 
So there have to be compromises somewhere. I don't want to track my phone's presence so closely that it drains the battery. On the other hand, I would like to have a fixed upper bound for my rules to know whether I am in or not.

**Comment by flatsiedatsie** [comment] 2020-08-07 06:28
I've created a new version with some small tweaks. The delay between normal scans has been made smaller again. Once it's available, please let me know how that affects the mobile phone detection.

**Comment by chas-iot** [comment] 2020-08-10 15:56
from my point of view, the high CPU utilisation is solved and so I think this issue may be closed.

**Comment by flatsiedatsie** [comment] 2020-08-10 16:15
Ok. Thanks for the help!

**Closed as completed by flatsiedatsie** 2020-08-10 16:15 UTC
